name: Deploy Examples
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: petitparser/dart-petitparser-examples
      - name: Install
        uses: dart-lang/setup-dart@v1
      - name: Build
        run: |
          dart pub get
          dart pub global activate webdev
          webdev build --release
          rm -rf build/packages
          touch .nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: main
          destination_dir: examples
          enable_jekyll: true
