name: Deploy Examples
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          repository: petitparser/dart-petitparser
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.0
      - name: Build Examples
        run: |
          cd petitparser_examples
          dart pub get
          dart pub global activate webdev
          webdev build --release
          rm -rf build/packages
          touch .nojekyll
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./petitparser_examples/build
          publish_branch: main
          destination_dir: examples
          enable_jekyll: true
